name: ramp_flutter
description: Official Flutter wrapper for Ramp
version: 1.0.1
homepage: https://ramp.network/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: network.ramp.ramp_flutter
        pluginClass: RampFlutterPlugin
      ios:
        pluginClass: RampFlutterPlugin
