name: ramp_flutter
description: Ramp Network for Flutter loads the Ramp widget in a Flutter WebView with a unified Dart API for iOS and Android.
version: 5.0.0
homepage: https://ramp.network/

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  webview_flutter: ^4.2.4
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.14.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: network.ramp.ramp_flutter
        pluginClass: RampFlutterPlugin
      ios:
        pluginClass: RampFlutterPlugin
