name: ramp_flutter
description: Ramp for Flutter is a simple wrapper for native iOS and Android Ramp SDKs. Unified API lets you write code once and use on any of the platforms. Ramp Flutter SDK supports iOS and Android platforms.
version: 3.0.0-alpha
homepage: https://ramp.network/

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: network.ramp.ramp_flutter
        pluginClass: RampFlutterPlugin
      ios:
        pluginClass: RampFlutterPlugin
