name: ramp_flutter
description: Ramp for Flutter is a simple wrapper for native iOS and Android Ramp SDKs. Unified API lets you write code once and use on any of the platforms. Ramp Flutter SDK supports iOS and Android platforms.
version: 2.0.0
homepage: https://ramp.network/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: network.ramp.ramp_flutter
        pluginClass: RampFlutterPlugin
      ios:
        pluginClass: RampFlutterPlugin
